name: hello world
on:
    push:
        branches:
            - main

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello world!"

            - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
            - run: echo Hello $GITHUB_ENV
